package events

type EndpointDetailEvent struct {
	ObjectType                 string
	ObjectName                 string
	Context                    string
	Disallow                   string
	Allow                      string
	DtmfMode                   string
	RtpIpv6                    string
	RtpSymmetric               string
	IceSupport                 string
	UsePtime                   string
	ForceRport                 string
	RewriteContact             string
	Transport                  string
	OutboundProxy              string
	MohSuggest                 string
	Field100Rel                string
	Timers                     string
	TimersMinSe                string
	TimersSessExpires          string
	Auth                       string
	OutboundAuth               string
	Aors                       string
	MediaAddress               string
	IdentifyBy                 string
	DirectMedia                string
	DirectMediaMethod          string
	TrustConnectedLine         string
	SendConnectedLine          string
	ConnectedLineMethod        string
	DirectMediaGlareMitigation string
	DisableDirectMediaOnNat    string
	Callerid                   string
	CalleridPrivacy            string
	CalleridTag                string
	TrustIdInbound             string
	TrustIdOutbound            string
	SendPai                    string
	SendRpid                   string
	SendDiversion              string
	Mailboxes                  string
	AggregateMwi               string
	MediaEncryption            string
	MediaEncryptionOptimistic  string
	UseAvpf                    string
	ForceAvp                   string
	MediaUseReceivedTransport  string
	OneTouchRecording          string
	InbandProgress             string
	CallGroup                  string
	PickupGroup                string
	NamedCallGroup             string
	NamedPickupGroup           string
	DeviceStateBusyAt          string
	T38Udptl                   string
	T38UdptlEc                 string
	T38UdptlMaxdatagram        string
	FaxDetect                  string
	T38UdptlNat                string
	T38UdptlIpv6               string
	ToneZone                   string
	Language                   string
	RecordOnFeature            string
	RecordOffFeature           string
	AllowTransfer              string
	UserEqPhone                string
	MohPassthrough             string
	SdpOwner                   string
	SdpSession                 string
	TosAudio                   string
	TosVideo                   string
	CosAudio                   string
	CosVideo                   string
	AllowSubscribe             string
	SubMinExpiry               string
	FromUser                   string
	FromDomain                 string
	MwiFromUser                string
	RtpEngine                  string
	DtlsVerify                 string
	DtlsRekey                  string
	DtlsCertFile               string
	DtlsPrivateKey             string
	DtlsCipher                 string
	DtlsCaFile                 string
	DtlsCaPath                 string
	DtlsSetup                  string
	SrtpTag32                  string
	RedirectMethod             string
	SetVar                     string
	MessageContext             string
	Accountcode                string
	PreferredCodecOnly         string
	DeviceState                string
	ActiveChannels             string
	SubscribeContext           string
	Allowoverlap               string
}

func (EndpointDetailEvent) EventTypeName() string {
	return "EndpointDetail"
}
